### DISCUSSION TITLE
Is there a depth limit for the personalisation of colors ?

### DISCUSSION THREAD

**Discussion by EricDepagneTAL** [sharkdp/vivid#181] [Q&A] [answered]
Hi.
I'm trying to personalize a little bit more the colors (like giving the python files the color of the python logo, or the gitignore files the color of the git logo), and I don't manage to get the latter correct.

In the `filetype.yml` the python file extension comes from
```
programming:
    source:
       python: [.py]
```
and I can color the python file by having 
```
programming:
  source:
    foreground: green

  python:
    foreground: '4482b4'
```

The `vcs`are defined the same way, except that there are one level deeper:
```
programming:
  tooling:
    vcs:
      git:
        - .gitignore
        - .gitmodules
        - .gitattributes
        - .gitconfig
        - .mailmap
      hg:
        - .hgrc
        - hgrc
```
If I try to define the color of the git files like this in my `personal_theme.yml` file:
```
programming:
  tooling:
    foreground: light_green
    vcs:
      git:
        foreground: 'f1502f'

```
then none of the files belonging the the `vcs`(git and hg) are colored, but if I comment out the `:git`then `all` of the vcs files are coloured in 
`f1502f` .

Is there a depth limit to define the colour, or am I doing something incorrectly?
Thanks.
