### ISSUE TITLE
Using vivid with pywal template (error)

### ISSUE THREAD

**Issue by vaskark** [sharkdp/vivid#113]
I'm trying to create a vivid theme for pywal and keep getting this error:

> Error: Unexpected type in YAML file

My pywal template:

```
colors:
  background_color: '{color0.strip}'
  white: '{color7.strip}'
  # bg: broken link
  red: '{color1.strip}'
  # executable
  bright_red: '{color9.strip}'
  # tooling
  green: '{color2.strip}'
  # source code
  bright_green: '{color10.strip}'
  # configuration, markup | bg: special
  yellow: '{color3.strip}'
  # directory | bg: fifo
  blue: '{color4.strip}'
  # archives
  bright_blue: '{color12.strip}'
  # media (bg: black)
  pink: '{color5.strip}'
  # symlink | bg: socket/door
  bright_pink: '{color13.strip}'
  # office, pdf
  cyan: '{color6.strip}'
  # block_device
  bright_cyan: '{color14.strip}'

  # foreground when background is diff
  black: '{color0.strip}'
  # licenses
  gray: '{color8.strip}'
  # unimportant files (lock files)
  darkgray: '7e7e7e'
  darkergray: '6a6a6a'

core:
  normal_text: white
  regular_file: white
  reset_to_normal: white

  directory:
    foreground: green
    font-style: underline

  symlink:
    foreground: pink

  multi_hard_link: pink

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: bright_pink

  door:
    foreground: black
    background: bright_pink

  block_device:
    foreground: bright_cyan
    background: darkergray

  character_device:
    foreground: bright_pink
    background: darkergray

  broken_symlink:
    foreground: black
    background: red

  missing_symlink_target:
    foreground: black
    background: red

  setuid: green

  setgid: green

  file_with_capability: green

  sticky_other_writable: green

  other_writable: green

  sticky: green

  executable_file:
    foreground: bright_red

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: bright_green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink
  background: black

office:
  foreground: cyan

archives:
  foreground: bright_blue
  font-style: underline

executable:
  foreground: bright_red

unimportant:
  foreground: darkgray

```
Any help would be greatly appreciated.
Thanks.
