### ISSUE TITLE
Nord theme isn't correct

### ISSUE THREAD

**Issue by driverkt** [sharkdp/vivid#129]
The sample Nord theme in the repo does not match the actual recommended Nord theme, seen [here](https://github.com/nordtheme/dircolors/blob/develop/src/dir_colors) -- [graphical depiction](https://www.nordtheme.com/ports/dircolors). 

Is there any plan to make these match? As it is, I'm not sure the "Nord" theme in this repo should be called "Nord" though it uses the Nord palette.

**Comment by jpcirrus** [comment]
Agreed. I created a custom Nord theme that combines the Nord `dircolors` and `Alacritty` (my terminal) themes, adjusted because currently multiple `font-style`s aren't possible in `vivid`. There are likely some personal tweaks which I have forgotten, but in my opinion it's an improvement and in the spirit of Nord:

```yaml
# Modified from bundled Nord
# Inspired by: https://github.com/nordtheme/alacritty
#              https://github.com/nordtheme/dircolors
# https://www.nordtheme.com/docs/colors-and-palettes

colors:
  nord0:  '2e3440'  # background
  nord1:  '3b4252'  # black
  nord2:  '434c5e'  # selection
  nord3:  '4c566a'  # brightblack
  nord4:  'd8dee9'  # foreground
  nord5:  'e5e9f0'  # white
  nord6:  'eceff4'  # brightwhite
  nord7:  '8fbcbb'  # brightcyan
  nord8:  '88c0d0'  # cyan
  nord9:  '81a1c1'  # blue
  nord10: '5e81ac'  # darkblue
  nord11: 'bf616a'  # red
  nord12: 'd08770'  # orange
  nord13: 'ebcb8b'  # yellow
  nord14: 'a3be8c'  # green
  nord15: 'b48ead'  # magenta

  dim-foreground: 'a5abb6'

core:
  normal_text:
    foreground: dim-foreground

  regular_file:
    foreground: nord4

  reset_to_normal:
    foreground: nord4
    background: nord0
    font-style: regular

  directory:
    foreground: nord10
    font-style: bold

  symlink:
    foreground: nord7

  multi_hard_link:
    foreground: nord7
    font-style: underline

  fifo:
    foreground: nord7
    font-style: bold

  socket:
    # NOTE: Also readline completion prefix
    foreground: nord13
    font-style: bold

  door:
    foreground: nord13
    font-style: italic

  block_device:
    foreground: nord13
    font-style: underline

  character_device:
    foreground: nord13

  broken_symlink:
    foreground: nord11

  missing_symlink_target:
    foreground: nord6
    background: nord11
    font-style: bold

  setuid:
    foreground: nord12
    font-style: bold

  setgid:
    foreground: nord12

  file_with_capability:
    foreground: nord12
    font-style: underline

  sticky_other_writable:
    foreground: nord6
    background: nord10
    font-style: bold

  other_writable:
    foreground: nord6
    background: nord10

  sticky:
    foreground: nord6
    background: nord10
    font-style: underline

  executable_file:
    foreground: nord9
    font-style: bold

text:
  special:
    foreground: nord4

  todo:
    foreground: nord4

  licenses:
    foreground: nord4

  configuration:
    foreground: nord4

  other:
    foreground: nord4

markup:
  web:
    foreground: nord4
  other:
    foreground: nord8

programming:
  source:
    foreground: nord9
  tooling:
    foreground: nord4

media:
  image:
    foreground: nord15

  audio:
    foreground: nord15

  video:
    foreground: nord15

  fonts:
    foreground: nord4

office:
  foreground: nord14

archives:
  foreground: nord5
  font-style: bold

executable:
  foreground: nord9
  font-style: bold

unimportant:
  foreground: nord3
```

**Comment by jpcirrus** [comment]
Here is the Nord theme as updated for vivid version 0.10.0. The theme now exactly matches the official theme at [Nord dircolors](https://github.com/nordtheme/dircolors) except for three changes:

1. The directory file type and directories with special permissions use nord10 instead of nord9, because against the terminal background (nord0) on Alacritty, nord9 looks too washed out.
2. Where there is a background colour, the foreground of nord4 is replaced by nord5, which I found made the text more legible.
3. The media/document file types don't all use nord14, but have been customised according to vivid categories. This is easily changed according to user preferences and required granularity.

```yaml
# Modified from bundled Nord
# Inspired by: https://github.com/nordtheme/alacritty
#              https://github.com/nordtheme/dircolors
# https://www.nordtheme.com/docs/colors-and-palettes

colors:
  nord0:  '2e3440'  # background
  nord1:  '3b4252'  # black
  nord2:  '434c5e'  # selection
  nord3:  '4c566a'  # brightblack
  nord4:  'd8dee9'  # foreground
  nord5:  'e5e9f0'  # white
  nord6:  'eceff4'  # brightwhite
  nord7:  '8fbcbb'  # brightcyan
  nord8:  '88c0d0'  # cyan
  nord9:  '81a1c1'  # blue
  nord10: '5e81ac'  # darkblue
  nord11: 'bf616a'  # red
  nord12: 'd08770'  # orange
  nord13: 'ebcb8b'  # yellow
  nord14: 'a3be8c'  # green
  nord15: 'b48ead'  # magenta

  dim-foreground: 'a5abb6'

core:
  normal_text:
    foreground: dim-foreground

  reset_to_normal:
    background: nord0
    foreground: nord4
    font-style: regular

# File Types

  regular_file:
    foreground: nord4

  directory:
    foreground: nord10  # nord9
    font-style: bold

  multi_hard_link:
    foreground: nord8
    font-style: underline

  symlink:
    foreground: nord8

  broken_symlink:
    foreground: nord11

  missing_symlink_target:
    # NOTE: Also used for readline completion shell builtin and function suffix
    background: nord11
    foreground: nord5  # nord4
    font-style: bold

  fifo:
    foreground: nord7
    font-style:
      - bold
      - underline

  character_device:
    foreground: nord13

  block_device:
    foreground: nord13
    font-style: underline

  door:
    foreground: nord13
    font-style: italic

  socket:
    # NOTE: Swapped with block device as used for readline completion prefix
    foreground: nord13
    font-style: bold

# File Permissions

  executable_file:
    foreground: nord7
    font-style: bold

  file_with_capability:
    foreground: nord4
    font-style:
      - bold
      - underline

  setuid:
    foreground: nord4
    font-style:
      - bold
      - underline

  setgid:
    foreground: nord4
    font-style:
      - bold
      - underline

  sticky:
    background: nord10  # nord9
    foreground: nord5   # nord4
    font-style: underline

  other_writable:
    background: nord10  # nord9
    foreground: nord5   # nord4
    font-style: bold

  sticky_other_writable:
    background: nord10  # nord9
    foreground: nord5   # nord4
    font-style:
      - bold
      - underline

# Document Types

archive:
  foreground: nord5
  font-style: bold

executable:
  foreground: nord7
  font-style: bold

markup:
  foreground: nord6
  web:
    foreground: nord4

media:
  foreground: nord15
  font:
    foreground: nord4

office:
  foreground: nord14

programming:
  source:
    foreground: nord7
  tooling:
    foreground: nord4
    build:
      foreground: nord4
      latex:
        foreground: nord7

text:
  foreground: nord4

unimportant:
  foreground: nord3
```
